# The location to use for storing cached Git repos
cachedir: /var/cache/r10k

# A list of git repositories to create
sources:
  # This will clone the git repository and instantiate an environment per
  # branch in /etc/puppetlabs/code/environments
  dynamic-environments:
    basedir: /etc/puppetlabs/code/environments
    ignore_branch_prefixes:
    - renovate/
    remote: https://github.com/alfsch/puppet-inventory.git
  static-environments:
    type: yaml
    basedir: /etc/puppetlabs/code/environments
